/// Flutter icons TablePick
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TablePick
///      fonts:
///       - asset: fonts/TablePick.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TablePick {
  TablePick._();

  static const _kFontFam = 'TablePick';
  static const String? _kFontPkg = null;

  static const IconData smallYet = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigYet = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallHeart = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigx = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallx = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_location = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_ios_new = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_location = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate_next = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigHeart = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
